Organiza/urls.py
#Cria as rotas do sistema

from django.conf.urls import *
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from app_usuario.views import *
from app_equipe.views import *
from app_base.views import *
from app_cliente.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Show),
    # url(r'^CriaUsuario',Cria_usuario),
    url(r'^CriaUsuario', Cria_Usuario),
    url(r'^lista_usuarios',lista_usuarios),
    url(r'^edita_usuario/(?P<nr_item>\d+)/$', edita_usuario),
    url(r'^item_usuario/(?P<nr_item>\d+)/$', detalha_usuario),
    url(r'^deleta_usuario/(?P<nr_item>\d+)/$', deleta_usuario),
    
    url(r'^CriaCliente', Cria_Cliente),
    url(r'^lista_clientes',lista_clientes),
    url(r'^item_cliente/(?P<nr_item>\d+)/$', detalha_Cliente),
    url(r'^Edita_Cliente/(?P<nr_item>\d+)/$', Edita_Cliente),
    url(r'^deleta_cliente/(?P<nr_item>\d+)/$', deleta_cliente),

    url(r'^Criasegmento', Cria_segmento),
    url(r'^lista_segmentos', lista_segmento),
     #url(r'^item_segmento/(?P<nr_item>\d+)/$', detalha_segmento),
    url(r'^CriaGrupo',Cria_Grupo),
    url(r'^lista_grupos', lista_grupo),
    url(r'^item_grupo/(?P<nr_item>\d+)/$', detalha_Grupo),
    url(r'^edita_grupo/(?P<nr_item>\d+)/$', edita_grupo),
    url(r'^deleta_grupo/(?P<nr_item>\d+)/$', deleta_grupo),
    
    url(r'^Crialideres',Cria_Lider),
    url(r'^lista_lideres', lista_lideres),
    url(r'^CriaColaborador',Cria_Colaborador),
    url(r'^lista_colaborador',lista_colaborador),
    url(r'^deleta_lider/(?P<nr_item>\d+)/$', deleta_lider),
    url(r'^deleta_colaborador/(?P<nr_item>\d+)/$', deleta_colaborador),

    url(r'^item_lider/(?P<nr_item>\d+)/$', detalha_lider),
    url(r'^item_colaborador/(?P<nr_item>\d+)/$', detalha_colaborador),

    url(r'^Criaequipe',Cria_Equipe),
    url(r'^lista_equipe',lista_equipe),
    url(r'^item_equipe/(?P<nr_item>\d+)/$', detalha_equipe),
    url(r'^edita_equipe/(?P<nr_item>\d+)/$', edita_equipe),
    url(r'^deleta_equipe/(?P<nr_item>\d+)/$', deleta_equipe),

    
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'login.html'}, name='logout'),
    #url(r'^chat',chat),
    #url(r'^accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_cliente/forms.py
from django import forms
from .models import *

PORTE = ((u'PEQUENO','PEQUENO'),(u'MEDIO','MEDIO'),(u'GRANDE','GRANDE'))

class FormSegmento(forms.ModelForm):
	nome = forms.CharField(max_length = 150, widget= forms.TextInput(attrs={'class':'form-control'}))
	class Meta:
		model = Segmento
		fields = ('nome',)

class FormCliente(forms.ModelForm):
	nome_fantasia = forms.CharField(max_length = 150, widget= forms.TextInput(attrs={'class':'form-control'}))
	cpf_cnpj = forms.CharField(max_length = 23, widget= forms.TextInput(attrs={'class':'form-control'}))
	segmento = forms.ModelChoiceField(queryset = Segmento.objects.all(), widget = forms.Select(attrs={"class":"form-control"}))
	porte_cliente = forms.ChoiceField(choices = PORTE, widget= forms.Select(attrs={'class':'form-control'}))
	telefone = forms.CharField(max_length = 11, widget= forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget= forms.TextInput(attrs={'class':'form-control'}))
	contato  = forms.CharField(max_length = 150, widget= forms.TextInput(attrs={'class':'form-control'}))
	cargo_contato = forms.CharField(max_length = 150, widget= forms.TextInput(attrs={'class':'form-control'}))
	endereco = forms.CharField(max_length = 150, widget= forms.TextInput(attrs={'class':'form-control'}))
	observacoes = forms.CharField(max_length = 150, widget= forms.Textarea(attrs={'class':'form-control'}))
	imagem_loja = forms.FileField()
	colaborador_responsavel = forms.ModelChoiceField(queryset = Usuario.objects.all(), widget = forms.Select(attrs={"class":"form-control"}))

	class Meta:
		model = Cliente
		fields = ('nome_fantasia','cpf_cnpj','segmento','porte_cliente','telefone','email','contato', 'cargo_contato','endereco','observacoes',
		 'imagem_loja','colaborador_responsavel')

class FormGrupo(forms.ModelForm):
	nome = forms.CharField(max_length = 150, widget= forms.TextInput(attrs={'class':'form-control'}))
	clientes = forms.ModelMultipleChoiceField(queryset = Cliente.objects.all(), widget = forms.SelectMultiple(attrs={'class':'form-control'}))
	class Meta:
		model = Grupo
		fields = ('nome','clientes')

templates/clientes/cria_cliente.html
{% extends "base2.html" %}

{% block conteudo %} 
<style type="text/css">
	#map {
        height: 100%;
      }
</style>

	{{form.errors}}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
	<form action="" method="post" enctype="multipart/form-data"> 
		{% csrf_token %}

		<div class="col-md-10 col-sm-10">
			{{form.nome_fantasia.label_tag}}
			{{form.nome_fantasia}}
		</div>
		<div class="col-md-5 col-sm-5">
			{{form.cpf_cnpj.label_tag}}
			{{form.cpf_cnpj}}
		</div>
		<div class="col-md-5 col-sm-5">
			{{form.segmento.label_tag}}
			{{form.segmento}}
		</div>
		<div class="col-md-5 col-sm-5">
			{{form.porte_cliente.label_tag}}
			{{form.porte_cliente}}
		</div>
		<div class="col-md-5 col-sm-5">
			{{form.telefone.label_tag}}
			{{form.telefone}}
		</div>
		<div class="col-md-5 col-sm-5">
			{{form.contato.label_tag}}
			{{form.contato}}
		</div>
		<div class="col-md-5 col-sm-5">
			{{form.email.label_tag}}
			{{form.email}}
		</div>
		<div class="col-md-5 col-sm-5">
			{{form.cargo_contato.label_tag}}
			{{form.cargo_contato}}
		</div>
		<div class="col-md-5 col-sm-5">
			{{form.endereco.label_tag}}
			{{form.endereco}}
			<!-- <input type="text" id="id_endereco" name="endereco" required maxlength="150" class="form-control"> -->
			<div id="map"></div>
			<script>
      // This example adds a search box to a map, using the Google Place Autocomplete
      // feature. People can enter geographical searches. The search box will return a
      // pick list containing a mix of places and predicted search terms.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -33.8688, lng: 151.2195},
          zoom: 13,
          mapTypeId: 'roadmap'
        });

        // Create the search box and link it to the UI element.
        var input = document.getElementById('id_endereco');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
      }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9uLo3PYO9SlY57qeXDrIO7I-rgqABriw&libraries=places&callback=initAutocomplete"
         async defer></script>

		</div>

		<div class="col-md-5 col-sm-5">
			{{form.imagem_loja.label_tag}}
			{{form.imagem_loja}}
		</div>

		<div class="col-md-12 col-sm-12">
			{{form.observacoes.label_tag}}
			{{form.observacoes}}
		</div>
		
		<div class="col-md-5 col-sm-5">
			{{form.colaborador_responsavel.label_tag}}
			{{form.colaborador_responsavel}}
		</div>

		<div class="col-md-10">
			<hr>
			<button type="submit" class="btn btn-success">Enviar</button>
			<button type="reset" class="btn btn-danger">Cancelar</button>
		</div>	
	</form>
{% endblock %}

templates/clientes/cria_grupo.html
{% extends "base2.html" %}
{% block conteudo %}
	<form method="post" action="">
		{% csrf_token %}
		<div class="col-md-10 col-sm-10">
			{{form.nome.label_tag}}
			{{form.nome}}
		</div>
		<div class="col-md-10 col-sm-10">
			{{form.clientes.label_tag}}
			{{form.clientes}}
		</div>	
		<div class="col-md-10">
			<hr>
			<button type="submit" class="btn btn-success">Enviar</button>
			<button type="reset" class="btn btn-danger">Cancelar</button>
		</div>	
	</form>
{% endblock %}

templates/clientes/cria_segmento.html
{% extends "base2.html" %}
{% block conteudo %}
	<form method="post" action="">
		<div class="col-md-10 col-sm-10">
			{% csrf_token %}
			{{form.nome.label_tag}}
			{{form.nome}}
		</div>	
		<div class="col-md-10">
			<hr>
			<button type="submit" class="btn btn-success">Enviar</button>
			<button type="reset" class="btn btn-danger">Cancelar</button>
		</div>	
	</form>
{% endblock %}

templates/clientes/item_clientes.html
{% extends "base2.html" %}
{% block conteudo %}
	<h1>{{item.nome_fantasia}} </h1>
	<div class="pull-right"><a href="/CriaCliente/"><i class="material-icons">&#xe7f0;</i></a>
		<a href="/Edita_Cliente/{{item.id}}/" title="Editar Cliente"><i class="material-icons">&#xE869;</i></a>
	</div>
	<div class="col-md-9 col-sm-9">	
		<span> do ramo {{item.segmento}}</span>
	</div>
	<div class="col-md-9 col-sm-9" style="width: 100%;">
		<div class="table-responsive">
			<table class="table">
		    <thead>
		      <tr style="color: #046350;">
		        <th>Cpf/Cnpj</th>
		        <th>Porte do Cliente</th>    
		         <th>TeleFone</th>    
		         <th>e-mail</th> 
		         <th>Pessoa Para Contato</th>    
		         <th>Cargo da Pessoa Para Contato</th>    
		         <th>Imagem </th>    
		         <th>Colaborador Responsável </th>    
		       </tr>

		      </thead>
		        <tbody>
		       
		       <tr>
		    
		        <td>{{ item.cpf_cnpj|upper }}</td>
		        
		        <td>{{ item.porte_cliente|upper }}</td>	
		        <td>{{ item.telefone|upper }}</td>
		        <td>{{ item.email }}</td>
		        <td>{{ item.contato }}</td>
		        <td>{{ item.cargo_contato }}</td>
		        <td><a href="{{ item.imagem_loja.url }}"><img src="{{ item.imagem_loja.url }}" width="100" class="img-thumbnail"></a></td>
		        <td>{{ item.colaborador_responsavel }}</td>

		      </tr>
		      
		    </tbody>
		  </table>
		</div>
	</div>
	<div class="col-sm-6 col-md-6">
  	<blockquote>{{item.observacoes}}</blockquote>
	</div>

	<div class="col-sm-6 col-md-6">
		{{item.endereco}}
		{% load easy_maps_tags cache %}

		{% cache 600 my_map item.endereco %}
		    {% easy_map item.endereco 300 400 %}
		{% endcache %}

	</div>

{% endblock %}

templates/clientes/item_grupos.html
{% extends "base2.html" %}
{% block conteudo %}
<div class="pull-right"><a href="/CriaGrupo/"><i class="material-icons">&#xe7f0;</i></a>
	<a href="/edita_grupo/{{item.id}}/" title="Editar Equipe"><i class="material-icons">&#xE869;</i></a>
</div>
	<h1>{{item.nome}} </h1>
	<h3>Lista de Clientes do Grupo</h3>
	<ul>
		{% for i in item.clientes.all %}
		<li><a href="/item_cliente/{{i.id}}">{{i}}</a></li>
		{%endfor%}
	</ul>
{% endblock %}

templates/clientes/item_segmento.html
{% extends "base2.html" %}
{% block conteudo %}
	{{item.nome}} 
{% endblock %}

templates/clientes/lista_clientes.html
{% extends "base2.html" %}
{% block conteudo %}
    
    <div class="col-md-12 col-lg-12">
        <div class="pull-right"><a href="/CriaCliente/"><i class="material-icons">&#xe7f0;</i></a></div>
        <h1 style="color:#046350;">Clientes</h1>
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Pesquisa</button>
        <br>          
        <div class="col-md-4 col-lg-4 collapse" id="demo">
        <form method="get">
            {{search.form.as_p}}
            <button type="submit" class="btn btn-success">Enviar</button>
            <button type="reset" class="btn btn-danger">Limpar</button>
        </div>
        <table class="table">
            <thead>
              <tr style="color: #046350;">
                    <th>Nome Fantasia</th>
                    <th>cpf/cnpj</th>
                    <th>Enddereço</th>                    
                  </tr>
                </thead>
                <tbody>
                {% for cliente in search.qs %}   
                <tr>
            
                <td><a href="/item_cliente/{{cliente.id}}" style="text-decoration: none; font-weight: bold; color: #d4bb77;">{{ cliente.nome_fantasia|upper }}</a></td>

                <td>{{cliente.cpf_cnpj}}</a></td>

                <td>{{cliente.endereco}}</a></td>
                
                <td>
                    
                    <button type="button" class="btn btn-default btn-sm"><a href="deleta_usuario/{{cliente.id}}">
                      <span class="glyphicon glyphicon-trash" style="color: #d4bb77;"></span><a href="/deleta_cliente/{{cliente.id}}">Excluir</a> 
                    </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

    </form>
    

<div class="pagination">
    <span class="step-links">
        {% if clientes.has_previous %}
            <a href="?page={{ clientes.previous_page_number }}">anterior</a>
        {% endif %}

        <span class="current">
            Página {{ clientes.number }} de {{ clientes.paginator.num_pages }}.
        </span>

        {% if clientes.has_next %}
            <a href="?page={{ clientes.next_page_number }}">próxima</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/clientes/lista_grupos.html
{% extends "base2.html" %}
{% block conteudo %}
    
    <div class="col-md-12 col-lg-12">
        <div class="pull-right"><a href="/CriaGrupo/"><i class="material-icons">&#xe7f0;</i></a></div>
        <h1 style="color:#046350;">Grupo de Clientes</h1>
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Pesquisa</button>
        <br>          
        <div class="col-md-4 col-lg-4 collapse" id="demo">
        <form method="get">
            {{search.form.as_p}}
            <button type="submit" class="btn btn-success">Enviar</button>
            <button type="reset" class="btn btn-danger">Limpar</button>
        </div>
        <table class="table">
            <thead>
              <tr style="color: #046350;">
                    <th>Nome</th>
                    
                  </tr>
                </thead>
                <tbody>
                {% for grupo in search.qs %}   
                <tr>
            
                <td><a href="/item_grupo/{{grupo.id}}" style="text-decoration: none; font-weight: bold; color: #d4bb77;">{{ grupo.nome|upper }}</a></td>

                
                <td>
                    
                    <button type="button" class="btn btn-default btn-sm"><a href="deleta_grupo/{{grupo.id}}">
                      <span class="glyphicon glyphicon-trash" style="color: #d4bb77;"></span><a href="/deleta_grupo/{{grupo.id}}">Excluir</a> 
                    </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

    </form>
    

<div class="pagination">
    <span class="step-links">
        {% if grupos.has_previous %}
            <a href="?page={{ grupos.previous_page_number }}">anterior</a>
        {% endif %}

        <span class="current">
            Página {{ grupos.number }} de {{ grupos.paginator.num_pages }}.
        </span>

        {% if grupos.has_next %}
            <a href="?page={{ grupos.next_page_number }}">próxima</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/clientes/lista_segmento.html
{% extends "base2.html" %}
{% block conteudo %}
    
    <div class="col-md-12 col-lg-12">
        <div class="pull-right"><a href="/CriaUsuario/"><i class="material-icons">&#xe7f0;</i></a></div>
        <h1 style="color:#046350;">Clientes</h1>
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Pesquisa</button>
        <br>          
        <div class="col-md-4 col-lg-4 collapse" id="demo">
        <form method="get">
            {{search.form.as_p}}
            <button type="submit" class="btn btn-success">Enviar</button>
            <button type="reset" class="btn btn-danger">Limpar</button>
        </div>
        <table class="table">
            <thead>
              <tr style="color: #046350;">
                    <th>Nome</th>
                    
                  </tr>
                </thead>
                <tbody>
                {% for segmento in search.qs %}   
                <tr>
            
                <td><a href="/item_segmento/{{segmento.id}}" style="text-decoration: none; font-weight: bold; color: #d4bb77;">{{ segmento.nome|upper }}</a></td>

                
                <td>
                    
                    <button type="button" class="btn btn-default btn-sm"><a href="deleta_usuario/{{cliente.id}}">
                      <span class="glyphicon glyphicon-trash" style="color: #d4bb77;"></span><a href="/deleta_cliente/{{cliente.id}}">Excluir</a> 
                    </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

    </form>
    

<div class="pagination">
    <span class="step-links">
        {% if segmentos.has_previous %}
            <a href="?page={{ segmentos.previous_page_number }}">anterior</a>
        {% endif %}

        <span class="current">
            Página {{ segmentos.number }} de {{ segmentos.paginator.num_pages }}.
        </span>

        {% if segmentos.has_next %}
            <a href="?page={{ segmentos.next_page_number }}">próxima</a>
        {% endif %}
    </span>
</div>
{% endblock %}